version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewProjectWithPkgVariableProject
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
- name: Package3
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
